implement get_token_uri in ProfileTokenUri module - issue #98
horuslabsio/karst-core pull request #107
Opened 2024-08-03 05:54 UTC by PavitraAgarwal21

**Checklist:**
  - [x] Basic SVG , felt252 Array  to ByteArray .
  - [ ] Into the base64 encoding .

2024-08-08 19:30 UTC, Darlington02 requested changes

2024-08-08 19:30 UTC, Darlington02 commented on src/base/token_uris/profile_token_uri.cairo
> +        svg.append('<svg width="200" height="200" x');
implementation looks good, but this is going to be a dynamic image. So I'd advise let's have the sample SVG as a string, then split it and append to the `svg` array, so we can easily adopt it for the main implementation. e.g

```rust
let sample_svg = '<svg width="200" height="200" xmlns="http://www.w3.org/2000/svg"><circle cx="100" cy="100" r="80" fill="red"/></svg>';
```

then split `sample_svg` into little chunks and append to the `svg` array.

2024-08-08 19:30 UTC, Darlington02 commented on src/base/token_uris/profile_token_uri.cairo
> +    fn get_attributes(tokenid: u256, mint_timestamp: u64) -> Array<felt252> {
not very relevant, but include spaces between the functions

2024-08-08 19:30 UTC, Darlington02 commented on src/base/token_uris/profile_token_uri.cairo
> +    fn get_json(tokenid: u256, mint_timestamp: u64) -> Array<felt252> {
parameter should be renamed to `token_id`

2024-08-08 19:30 UTC, Darlington02 commented on src/base/token_uris/profile_token_uri.cairo
> +        let tokenid_felt: felt252 = tokenid.try_into().unwrap();
let's be consistent with our naming style e.g this should be `token_id_felt`

2024-08-08 19:30 UTC, Darlington02 commented on src/base/token_uris/profile_token_uri.cairo
> +        let tokenid_byte: ByteArray = tokenid_felt.try_into().unwrap();
`token_id_byte`

2024-08-08 19:30 UTC, Darlington02 commented on src/base/token_uris/profile_token_uri.cairo
> +        let tokenid_byte_len: felt252 = tokenid_byte.len().try_into().unwrap();
`token_id_byte_len`

2024-08-08 19:30 UTC, Darlington02 commented on src/base/token_uris/profile_token_uri.cairo
> +        let tokenid_felt: felt252 = tokenid.try_into().unwrap();
`token_id_felt`

2024-08-08 19:30 UTC, Darlington02 commented on src/base/token_uris/profile_token_uri.cairo
>      pub fn get_token_uri(token_id: u256, mint_timestamp: u64) -> ByteArray {
Finally let's include tests to check the implementation works as expeccted.

2024-08-09 05:54 UTC, PavitraAgarwal21 commented on src/base/token_uris/profile_token_uri.cairo
> +        svg.append('<svg width="200" height="200" x');
svg  cant be string because the value does not fit within the range of felt252 , and if we use the bytearray to represent the long string , the problem is double quotes with in the double quotes , so only the solution would be the during the formation of the dynamic svg/image we can do something like this https://github.com/cienicera/nft-svg-onchain-poc/blob/main/src/svg/image.cairo

2024-08-09 10:30 UTC, PavitraAgarwal21 commented on src/base/token_uris/profile_token_uri.cairo
>      pub fn get_token_uri(token_id: u256, mint_timestamp: u64) -> ByteArray {
it does not break against a longer svg as we uses the array

2024-08-09 10:35 UTC, Darlington02 commented on src/base/token_uris/profile_token_uri.cairo
>      pub fn get_token_uri(token_id: u256, mint_timestamp: u64) -> ByteArray {
Fair, but let’s still include tests

2024-08-10 11:56 UTC, merged

2024-08-10 11:56 UTC, Darlington02 commented
@allcontributors add @PavitraAgarwal21 for code