Community Features
horuslabsio/karst-core pull request #114
Opened 2024-09-30 14:37 UTC by mubarak23

2024-10-01 00:29 UTC, Darlington02 requested changes

2024-10-01 00:29 UTC, Darlington02 commented on src/community/community.cairo
> +            assert(owner_community_id != community_id, "Not Community Owner");
I'd prefer you use the community_id to get it's owner, and then compare against `get_caller_address`

2024-10-01 00:29 UTC, Darlington02 commented on src/community/community.cairo
> +            assert(commuity.community_owner == community_owner, "Not Community Owner");
not just community owners, but community mods should be able to ban users

2024-10-01 00:29 UTC, Darlington02 commented on src/community/community.cairo
> +
TODO:

- If gatekeep_type is PermissionedGating, let's iterate through permissioned_addresses and store in `gatekeep_permissioned_addresses`.
- If it's PaidGating let's take in the entry_fee and add it to the `CommunityGateKeep` struct.

2024-10-01 00:29 UTC, Darlington02 commented on src/community/community.cairo
> +            permissioned_addresses: Vec<ContractAddress>
permissioned_addresses should rather be an array

2024-10-01 00:29 UTC, Darlington02 commented on src/community/community.cairo
> +            self.communities.write(community_id, community);
let's also update premium_subscription_status to true

2024-10-01 00:29 UTC, Darlington02 commented on src/community/community.cairo
> +            (community.community_type, community.community_premium_status)
return type seems exchanged?

2024-10-02 06:28 UTC, mubarak23 commented on src/community/community.cairo
> +
for this 

`If it's PaidGating let's take in the entry_fee and add it to the CommunityGateKeep struct.`

the function will need an extra argument, called `entry_fee` @Darlington02

2024-10-08 23:53 UTC, merged