Feat/channel
horuslabsio/karst-core pull request #123
Opened 2024-10-11 15:57 UTC by Darlington02

2024-10-12 14:48 UTC, mubarak23 commented on src/channel/channel.cairo
> +                channel_nft_address: 1.try_into().unwrap(),
we should have a deploy channel NFT function that return the contract address and use it here.

2024-10-12 14:50 UTC, mubarak23 commented on src/channel/channel.cairo
> +                community_id: community_id,
we need to check community exist

2024-10-12 15:43 UTC, mubarak23 requested changes

2024-10-12 15:43 UTC, mubarak23 commented on src/channel/channel.cairo
> +
after the checks, let move the remaining part of this function into an internal function, the same way we did for join_channel

2024-10-12 15:43 UTC, mubarak23 commented on src/channel/channel.cairo
> +            channel.channel_censorship = censorship_status;
let do this instead, 

```
let update_channel = ChannelDetails {channel.channel_censorship: censorship_status, ..channel};
 self.channels.write(channel_id, update_channel);
```
its a lot cleaner, this way we know we are retaining the remaining details.

2024-10-12 15:43 UTC, mubarak23 commented on src/channel/channel.cairo
> +        fn _deploy_channel_nft(
let call this function inside `create_channel`

2024-10-12 15:43 UTC, mubarak23 commented on src/channel/channel.cairo
> +        fn is_channel_member(
we should return a tuple of member status and ChannelMember i.e `(is_member, channel_member_detail)`, 

we will need the `channel_member_detail` particularly in test, when we are test each item in the channel member struct is set 

also checking if channel_token_id is minted or burned

2024-10-12 15:43 UTC, mubarak23 commented on src/channel/channel.cairo
> +        fn _initializer(ref self: ComponentState<TContractState>, channel_nft_classhash: felt252) {
we should we have an external function that call this

2024-10-13 23:56 UTC, Darlington02 commented on src/channel/channel.cairo
> +            let channel_id = self.channel_counter.read() + 1;
we do, check the `_initializer` internal function

2024-10-13 23:57 UTC, Darlington02 commented on src/channel/channel.cairo
> +                channel_nft_address: 1.try_into().unwrap(),
that makes sense, skipped it, will implement now:)

2024-10-14 00:10 UTC, Darlington02 commented on src/channel/channel.cairo
> +            let membership_status = community_instance
oh yeah, I think you implemented that recently. atm it returns just bool. will fix after resolving conflicts with main

2024-10-14 00:18 UTC, Darlington02 commented on src/channel/channel.cairo
> +        fn _initializer(ref self: ComponentState<TContractState>, channel_nft_classhash: felt252) {
nope. it will be called within the constructor of the inheriting the contract

2024-10-14 00:55 UTC, merged