Publish Mirror Function
horuslabsio/karst-core pull request #27
Opened 2024-06-11 07:23 UTC by mubarak23

Work on issue: #23 
- implement the mirror function from publish contract
- write the unit test for the function

2024-06-11 07:54 UTC, codeWhizperer commented
GM @mubarak23, could you add more test cases for the mirror function?

2024-06-11 07:57 UTC, mubarak23 commented
> GM @mubarak23, could you add more test cases for the mirror function?

i can add
 should_panic test,

2024-06-11 09:27 UTC, codeWhizperer commented
> > GM @mubarak23, could you add more test cases for the mirror function?
> 
> i can add should_panic test,

@mubarak23 test for the pointed_profile_address and root_profile_address and also test for two or more user mirroring a post

2024-06-11 10:02 UTC, Darlington02 reviewed
just a few typo corrections

2024-06-11 10:02 UTC, Darlington02 commented on src/publication/publication.cairo
> +    pub struct MirrowCreated {
should be `MirrorCreated` not `MirrowCreated`

2024-06-11 10:02 UTC, Darlington02 commented on src/publication/publication.cairo
> +        MirrowCreated: MirrowCreated,
MirrorCreated

2024-06-11 10:02 UTC, Darlington02 commented on tests/test_publication.cairo
> +fn test_publish_mirrow() {
test_publish_mirror

2024-06-11 10:02 UTC, Darlington02 commented on tests/test_publication.cairo
> +    let mirrow_params = MirrorParams {
mirror_params

2024-06-11 10:06 UTC, mubarak23 commented on src/publication/publication.cairo
> +    pub struct MirrowCreated {
Seen it , i will correct it

2024-06-11 10:21 UTC, codeWhizperer commented
> > > > GM @mubarak23, could you add more test cases for the mirror function?
> > > 
> > > 
> > > i can add should_panic test,
> > 
> > 
> > @mubarak23 test for the pointed_profile_address and root_profile_address and also test for two or more user mirroring a post
> 
> can you please explain further what you mean by this
> 
> `test for the pointed_profile_address and root_profile_address `

The `pointed_profile_address` is the profile that mirrored a post, and the `root_profile_address` is the profile_address of the user who created the post. So basically, you should test for the `root_profile_address` of the post being mirrored and the address that mirrored the post `pointed_profile_address` to ensure the values are correct in storage.

2024-06-11 10:25 UTC, codeWhizperer commented
> > > > > GM @mubarak23, could you add more test cases for the mirror function?
> > > > 
> > > > 
> > > > i can add should_panic test,
> > > 
> > > 
> > > @mubarak23 test for the pointed_profile_address and root_profile_address and also test for two or more user mirroring a post
> > 
> > 
> > can you please explain further what you mean by this
> > `test for the pointed_profile_address and root_profile_address `
> 
> The `pointed_profile_address` is the profile that mirrored a post, and the `root_profile_address` is the profile_address of the user who created the post. So basically, you should test for the `root_profile_address` of the post being mirrored and the address that mirrored the post `pointed_profile_address` to ensure the values are correct in storage.

@mubarak23 Do you understand?

2024-06-11 10:27 UTC, mubarak23 commented
> > > > > > GM @mubarak23, could you add more test cases for the mirror function?
> > > > > 
> > > > > 
> > > > > i can add should_panic test,
> > > > 
> > > > 
> > > > @mubarak23 test for the pointed_profile_address and root_profile_address and also test for two or more user mirroring a post
> > > 
> > > 
> > > can you please explain further what you mean by this
> > > `test for the pointed_profile_address and root_profile_address `
> > 
> > 
> > The `pointed_profile_address` is the profile that mirrored a post, and the `root_profile_address` is the profile_address of the user who created the post. So basically, you should test for the `root_profile_address` of the post being mirrored and the address that mirrored the post `pointed_profile_address` to ensure the values are correct in storage.
> 
> @mubarak23 Do you understand?

Yes

2024-06-11 16:12 UTC, mubarak23 commented
@codeWhizperer two or more users mirroring a post test has been added

2024-06-12 10:28 UTC, Darlington02 requested changes

2024-06-12 10:28 UTC, Darlington02 commented on src/interfaces/IPublication.cairo
> +    fn mirror(
the `mirror` function is not a getter function. shouldn't be under getters

2024-06-12 10:28 UTC, Darlington02 commented on src/publication/publication.cairo
> +            let pubIdAssigned = IKarstProfileDispatcher {
`pubIdAssigned` doesn't seem like a good name to call this variable. I'd rather call it `profileDispatcher`, since it simply just instantiates the dispatcher

2024-06-12 10:28 UTC, Darlington02 commented on tests/test_publication.cairo
> +    let actual_pub_id_assigned = IKarstProfileDispatcher {
same here. `actual_pub_id_assigned` doesn't seem like a good name to call this variable. I'd rather call it `profileDispatcher`, since it simply just instantiates the dispatcher

2024-06-12 10:28 UTC, Darlington02 commented on src/publication/publication.cairo
Take out the entire interface section here. unnecessary code duplication, as you can simply just import the IPublication interface from the `interfaces` folder

2024-06-12 10:29 UTC, Darlington02 commented
@mubarak23 left some extra comments, once addressed should be good to go.

2024-06-12 10:48 UTC, mubarak23 commented
changes made base on the review requested @Darlington02 kindly review

2024-06-12 10:54 UTC, merged