Implemented the link and unlink functions in HandleRegistry.
horuslabsio/karst-core pull request #55
Opened 2024-06-14 08:12 UTC by kenkomu

Implemented the link and unlink functions in the HandleRegistry smart contract and added test to the respective functions

2024-06-17 19:40 UTC, Darlington02 requested changes

2024-06-19 17:11 UTC, kenkomu commented on src/namespaces/handle_registry.cairo
>      //                            IMPORT
I have run the scarb fmt --check and there is no issue with the handle_registry.cairo file.

2024-06-19 17:11 UTC, kenkomu commented on src/namespaces/handle_registry.cairo
> +            self.handle_to_profile_address.write(handle_id, profile_address);
I have implemented it.

2024-06-19 17:11 UTC, kenkomu commented on src/namespaces/handle_registry.cairo
> +            emit_event(Event::Linked(HandleLinked {
I have implemented it.

2024-06-19 17:12 UTC, kenkomu commented on src/namespaces/handle_registry.cairo
> +            self.handle_to_profile_address.remove(handle_id);
I have implemented it.

2024-06-19 17:12 UTC, kenkomu commented on src/namespaces/handle_registry.cairo
> +            emit_event(Event::Unlinked(HandleUnlinked {
I have implemented it.

2024-06-19 17:12 UTC, kenkomu commented on src/namespaces/handle_registry.cairo
> +            self.handle_to_profile_address.remove(handle_id);
I have implemented it.

2024-06-19 17:12 UTC, kenkomu commented on tests/test_handle_registry.cairo
I have also implemented the test as requested.

2024-06-19 17:13 UTC, kenkomu commented
@Darlington02 could you review the code?

2024-06-20 09:50 UTC, Darlington02 commented
> @Darlington02 could you review the code?

both the build and test workflows still fails

2024-06-20 10:13 UTC, Darlington02 requested changes

2024-06-20 10:13 UTC, Darlington02 commented on tests/test_handle_registry.cairo
> +fn deploy_handle_registry() -> (HandleRegistry, ContractAddress) {
do this within the test setup `__setup__` for consistency. review other tests

2024-06-20 10:13 UTC, Darlington02 commented on tests/test_handle_registry.cairo
> +fn fetch_linked_event(handle_registry_address: ContractAddress) -> HandleLinked {
do this within the test setup `__setup__` for consistency. review other tests

2024-06-20 10:13 UTC, Darlington02 commented on tests/test_handle_registry.cairo
> +fn caller() -> ContractAddress {
do this within the test setup `__setup__` for consistency. review other tests

2024-06-20 10:13 UTC, Darlington02 commented on tests/test_handle_registry.cairo
> +    let linked_event = fetch_linked_event(handle_registry_address);
this is invalid and not the right way to test for emitted events. you basically are not testing against the emitted events, but against values you manually came up with. same thing for the test_unlink_should_emit_events.

And once again, you're still not testing that the functions you wrote works. I'm more interested in that, than the events you're testing for.

2024-06-20 10:15 UTC, Darlington02 commented
@kenkomu all other PRs currently in drafts are awaiting your PR. Please look into the requested changes before EOD, or I might have to delegate this issue to someone else to conserve time.

2024-06-20 10:20 UTC, kenkomu commented
> @kenkomu all other PRs currently in drafts are awaiting your PR. Please look into the requested changes before EOD, or I might have to delegate this issue to someone else to conserve time.

@Darlington02 I made a push yesterday as requested by you. Could you please review the code?

2024-06-21 09:12 UTC, kenkomu commented
@Darlington02 I have made changes as requested and put the error message in the error.cairo file I have also made an update in the test for the link and unlink functions. If there is a need for a change in the test, please assist me.

2024-06-21 09:56 UTC, Darlington02 commented
> @Darlington02 I have made changes as requested and put the error message in the error.cairo file I have also made an update in the test for the link and unlink functions. If there is a need for a change in the test, please assist me.

there's a conflict with your PR, please look into it.

2024-06-23 22:05 UTC, MarvyNwaokobia commented
Hey @kenkomu any update on this?
I need this done so i can submit my PR

2024-06-24 01:35 UTC, closed without merging