test: test karstnft
horuslabsio/karst-core pull request #77
Opened 2024-06-29 12:46 UTC by Jemiiah

2024-07-01 15:33 UTC, Darlington02 requested changes

2024-07-01 15:33 UTC, Darlington02 commented on tests/test_karstnft.cairo
> +fn test_nft_count_on_init_is_zero() {
in here, I expected you'd be checking that the total supply on deployment is zero, not the balance of a user

2024-07-01 15:33 UTC, Darlington02 commented on tests/test_karstnft.cairo
> +fn test_user_token_id_on_init_is_zero() {
you can delete this test case, not useful imo

2024-07-01 15:33 UTC, Darlington02 commented on tests/test_karstnft.cairo
> +
add two additional test cases to check for the name, symbol of the NFT

2024-07-01 15:49 UTC, Jemiiah commented on tests/test_karstnft.cairo
> +
Thank you will make necessary changes

2024-07-02 16:41 UTC, Jemiiah commented on tests/test_karstnft.cairo
> +fn test_nft_count_on_init_is_zero() {
I checked the ERC721 component interface on openzeppelin but I couldn't find a function that returns the total supply. Do you have an idea of how to get it?

2024-07-05 00:08 UTC, merged

2024-07-05 00:10 UTC, Darlington02 commented
@allcontributors please add @Jemiiah as contributor for code